# Generated by Django 6.0.3 on 2026-03-29 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Persona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("telefono", models.CharField(max_length=15)),
                ("fecha_nacimiento", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="TipoTarea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField(blank=True)),
                ("prioridad", models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="Tarea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                ("completada", models.BooleanField(default=False)),
                (
                    "tipo_tarea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="proyecto.tipotarea",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TareaAsignada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_asignacion", models.DateTimeField(auto_now_add=True)),
                ("completada", models.BooleanField(default=False)),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="proyecto.persona",
                    ),
                ),
                (
                    "tarea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="proyecto.tarea"
                    ),
                ),
            ],
            options={
                "unique_together": {("tarea", "persona")},
            },
        ),
    ]
